- name: UnDeploy Moonshot Application on Kubernetes
  hosts: localhost
  gather_facts: false
  become: true # Ensures root privileges where needed
  environment:
    KUBECONFIG: /home/vagrant/.kube/config # Define explicitamente o caminho do kubeconfig
  roles:
    - role: k8s-postgres-undeploy
      tags: ["postgres-deploy"]

    - role: k8s-moon-undeploy
      tags: ["moonshot-deploy"]

  vars:
    build: true # Set build to true here
