- name: Delete PostgreSQL service
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ db_host }}"
        namespace: default
  when: delete_data | bool      
  tags: postgres

- name: Wait - Delete PostgreSQL service 
  kubernetes.core.k8s_info:
    kind: Service
    namespace: default
    name:
      - app=postgres
  register: info_service
  retries: 5
  delay: 100
  until: info_service.resources | length == 0
  when: delete_data | bool
  tags: postgres

- name: Delete PostgreSQL Deployment 
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: postgres-deployment
        namespace: default
    wait: true
    wait_timeout: 300
    force: true
  when: delete_data | bool
  tags: postgres


- name: Wait - Delete PostgreSQL Deployment 
  kubernetes.core.k8s_info:
    kind: Deployment
    namespace: default
    name:
      - app=postgres
  register: info_deployment
  retries: 5
  delay: 100
  until: info_deployment.resources | length == 0
  when: delete_data | bool
  tags: postgres

- name: Delete PostgreSQL PVC
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ pvc_name }}"
        namespace: default
  when: delete_data | bool
  tags: postgres

- name: Wait - Delete PostgreSQL PVC
  kubernetes.core.k8s_info:
    kind: PersistentVolumeClaim
    namespace: default
    name:
      - app=postgres
  register: info_pvc
  retries: 5
  delay: 100
  until: info_pvc.resources | length == 0
  when: delete_data | bool
  tags: postgres

- name: Delete postgres-secret
  kubernetes.core.k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: postgres-secret
        namespace: default
  when: delete_data | bool
  tags: moonshot
