apiVersion: autoscaling/v2 
kind: HorizontalPodAutoscaler
metadata:
  name: moonshot-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 4
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: moonshot-deployment
  # stabilizationWindowSeconds: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75