apiVersion: v1
kind: Secret
metadata:
  name: moon-secret
  namespace: default
type: Opaque
data:
    DB_HOST: "{{ db_host | b64encode }}"
    DB_NAME: "{{ db_name | b64encode }}"
    DB_USER: "{{ db_username | b64encode }}"
    DB_PASSWORD: "{{ db_password | b64encode }}"
