---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moonshot-pvclaim
  labels:
    app: moonshot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: standard
