apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonshot-deployment
  namespace: default
spec:
  replicas: 1  # Número inicial de réplicas
  selector:
    matchLabels:
      app: moonshot
  template:
    metadata:
      labels:
        app: moonshot
    spec:
      containers:
        - name: moonshot
          image: "{{ moonshot_image }}"
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: moon-secret
                  key: DB_HOST

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: moon-secret
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: moon-secret
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: moon-secret
                  key: DB_PASSWORD

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"  # Recurso mínimo de CPU reservado por pod
              memory: "128Mi"  # Recurso mínimo de memória reservado por pod
