---
- name: Moonshot Application Undeploy
  hosts: localhost
  tasks:
    # Task 1: Delete Kubernetes Resources
    - name: Delete Kubernetes Deployment
      kubernetes.core.k8s:
        state: absent
        kind: Deployment
        namespace: default
        name: moonshot-deployment
        kubeconfig: "{{ kubeconfig_path }}"
      ignore_errors: yes # Continue if the resource doesn't exist

    - name: Delete Kubernetes Service
      kubernetes.core.k8s:
        state: absent
        kind: Service
        namespace: default
        name: moonshot-service
        kubeconfig: "{{ kubeconfig_path }}"
      ignore_errors: yes

    - name: Delete Persistent Volume Claims (PVCs)
      kubernetes.core.k8s:
        state: absent
        kind: PersistentVolumeClaim
        namespace: default
        name: moonshot-pvc
        kubeconfig: "{{ kubeconfig_path }}"
      ignore_errors: yes

    - name: Delete ConfigMaps
      kubernetes.core.k8s:
        state: absent
        kind: ConfigMap
        namespace: default
        name: moonshot-config
        kubeconfig: "{{ kubeconfig_path }}"
      ignore_errors: yes

    # Task 2: Cleanup Docker Images (if applicable)
    - name: Remove Docker images
      community.docker.docker_image:
        name: moonshot-app
        state: absent
      ignore_errors: yes
