apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
    DB_NAME: "{{ db_name | b64encode }}"
    DB_USER: "{{ db_username | b64encode }}"
    DB_PASSWORD: "{{ db_password | b64encode }}"
    DB_TRUST: "{{ db_trust | b64encode }}"
